### ISSUE TITLE
"TypeError: Object.fromEntries is not a function" when creating a new locale

### ISSUE THREAD

**Issue by lufte** [umputun/remark42#644]
I'm following the instructions [here](https://github.com/umputun/remark42/blob/master/docs/translation.md) to add a new locale, but running `npm run generate-langs` results in the following error:

```
lufte@lufte-thinkpad:~/projects/remark42/frontend$ npm run generate-langs

> remark-ui@0.1.0 generate-langs /home/lufte/projects/remark42/frontend
> npm run extract-messages && node ./tasks/generateDictionary.js


> remark-ui@0.1.0 extract-messages /home/lufte/projects/remark42/frontend
> formatjs extract --out-file=./extracted-messages/messages.json './app/**/*.{js,jsx,ts,tsx}'

/home/lufte/projects/remark42/frontend/tasks/generateDictionary.js:11
  return Object.fromEntries(Object.entries(dictionary).filter(([key]) => existKeys.includes(key)));
                ^

TypeError: Object.fromEntries is not a function
    at removeAbandonedKeys (/home/lufte/projects/remark42/frontend/tasks/generateDictionary.js:11:17)
    at locales.forEach.locale (/home/lufte/projects/remark42/frontend/tasks/generateDictionary.js:33:17)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/lufte/projects/remark42/frontend/tasks/generateDictionary.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remark-ui@0.1.0 generate-langs: `npm run extract-messages && node ./tasks/generateDictionary.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remark-ui@0.1.0 generate-langs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lufte/.npm/_logs/2020-04-07T01_32_02_023Z-debug.log
```

I'm running Node 10, and the README stipulates that I need Node 8 or higher, but it seems that `Object.fromEntries` is not supported until Node 12.11.

**Comment by umputun** [comment]
cc: @Mavrin @akellbl4

**Comment by akellbl4** [comment]
@lufte hi! You need to use node in version 12 or higher

**Comment by akellbl4** [comment]
Hi @lufte, you should use node 12.11 or higher. We will change readme, thanks for noticing us. Current version of node is correctly mentioned in package.json

**Comment by akellbl4** [comment]
It was not exactly 12.11 in `package.json`. Now I added actual information in PR.
